// Pure cross-window move logic (cross-window-drag ticket 04). Sibling module
// to `gridState.ts`, which only ever holds ONE window's state — a move here
// spans two independent `GridState`s (source window, target window) and
// returns both updated. Both windows run this same function locally against
// their own state, triggered by the cross-window event later tickets build;
// no shared process state is needed, and this module stays free of
// React/`@tauri-apps` imports for the same reason `gridState.ts` is.

import {
  type GridState,
  type Pane,
  type TerminalTab,
  withoutTab,
} from "./gridState";

export interface CrossWindowMoveResult {
  source: GridState;
  target: GridState;
}

export type CrossWindowDragPayload =
  | { kind: "pane"; paneId: string }
  | {
      kind: "tab";
      paneId: string;
      tabId: string;
      /** Pre-generated by the caller for the "target is an empty slot"
       * branch, same convention as `moveTerminalTabToEmptySlot`'s
       * `newPaneId` — this module never mints ids itself. Unused (and
       * harmless to pass) when the drop resolves to an insert or a no-op. */
      newPaneId: string;
    };

/**
 * Resolves a pane or single-tab drag dropped at `targetSlotIndex` of
 * `target` against `source`. No-op (both states referentially unchanged)
 * for any invalid input — unknown source pane/tab, an out-of-range target
 * index, or (tab payload only) a project mismatch with no empty target slot.
 *
 * Pane payload: an occupied target slot swaps both panes across windows
 * (analogous to `swapPanes`); an empty one moves the pane over, source slot
 * becomes empty (analogous to `movePaneToEmptySlot`). No project
 * restriction — the pane brings its own project along.
 *
 * Tab payload: a target pane of the SAME project gets the tab inserted,
 * active after drop (analogous to `moveTerminalTab`); an empty target slot
 * gets a brand-new pane containing just this tab (analogous to
 * `moveTerminalTabToEmptySlot`); a target pane of a DIFFERENT project with
 * no empty slot available is a no-op — no third window is auto-created as a
 * rescue.
 */
export function moveAcrossWindows(
  source: GridState,
  target: GridState,
  payload: CrossWindowDragPayload,
  targetSlotIndex: number,
): CrossWindowMoveResult {
  const noop: CrossWindowMoveResult = { source, target };
  if (targetSlotIndex < 0 || targetSlotIndex >= target.slots.length) return noop;

  if (payload.kind === "pane") {
    return movePane(source, target, payload.paneId, targetSlotIndex, noop);
  }
  return moveTab(
    source,
    target,
    payload.paneId,
    payload.tabId,
    payload.newPaneId,
    targetSlotIndex,
    noop,
  );
}

function movePane(
  source: GridState,
  target: GridState,
  paneId: string,
  targetSlotIndex: number,
  noop: CrossWindowMoveResult,
): CrossWindowMoveResult {
  const sourceIndex = source.slots.findIndex((slot) => slot?.paneId === paneId);
  if (sourceIndex === -1) return noop;
  const movedPane = source.slots[sourceIndex] as Pane;
  const targetSlot = target.slots[targetSlotIndex];

  const nextSourceSlots = source.slots.slice();
  const nextTargetSlots = target.slots.slice();

  if (targetSlot) {
    // Swap: both panes fully change windows — each window treats its
    // incoming pane as newly arrived, the same way a same-window swap
    // never has to (nothing "arrives from outside" there).
    nextSourceSlots[sourceIndex] = targetSlot;
    nextTargetSlots[targetSlotIndex] = movedPane;
    return {
      source: {
        ...source,
        slots: nextSourceSlots,
        focusedPaneId: targetSlot.paneId,
        maximizedPaneId:
          source.maximizedPaneId === paneId ? null : source.maximizedPaneId,
      },
      target: {
        ...target,
        slots: nextTargetSlots,
        focusedPaneId: movedPane.paneId,
        maximizedPaneId:
          target.maximizedPaneId === targetSlot.paneId
            ? null
            : target.maximizedPaneId,
      },
    };
  }

  // Move to an empty slot: the pane leaves the source window entirely.
  nextSourceSlots[sourceIndex] = null;
  nextTargetSlots[targetSlotIndex] = movedPane;
  return {
    source: {
      ...source,
      slots: nextSourceSlots,
      focusedPaneId:
        source.focusedPaneId === paneId
          ? (nextSourceSlots.find((slot): slot is Pane => slot !== null)?.paneId ?? null)
          : source.focusedPaneId,
      maximizedPaneId:
        source.maximizedPaneId === paneId ? null : source.maximizedPaneId,
    },
    target: { ...target, slots: nextTargetSlots, focusedPaneId: movedPane.paneId },
  };
}

function moveTab(
  source: GridState,
  target: GridState,
  sourcePaneId: string,
  tabId: string,
  newPaneId: string,
  targetSlotIndex: number,
  noop: CrossWindowMoveResult,
): CrossWindowMoveResult {
  const sourceIndex = source.slots.findIndex((slot) => slot?.paneId === sourcePaneId);
  if (sourceIndex === -1) return noop;
  const sourcePane = source.slots[sourceIndex] as Pane;
  const tabIndex = sourcePane.tabs.findIndex(
    (tab) => tab.kind === "terminal" && tab.tabId === tabId,
  );
  if (tabIndex === -1) return noop;
  const movedTab = sourcePane.tabs[tabIndex] as TerminalTab;

  const targetSlot = target.slots[targetSlotIndex];
  if (targetSlot && targetSlot.projectPath !== sourcePane.projectPath) return noop;

  const nextTargetSlots = target.slots.slice();
  let nextTargetPaneId: string;
  if (targetSlot) {
    nextTargetPaneId = targetSlot.paneId;
    nextTargetSlots[targetSlotIndex] = {
      ...targetSlot,
      tabs: [...targetSlot.tabs, movedTab],
      activeTabId: movedTab.tabId,
    };
  } else {
    nextTargetPaneId = newPaneId;
    nextTargetSlots[targetSlotIndex] = {
      paneId: newPaneId,
      projectPath: sourcePane.projectPath,
      tabs: [movedTab],
      activeTabId: movedTab.tabId,
    };
  }

  const nextSourceSlots = source.slots.slice();
  nextSourceSlots[sourceIndex] =
    sourcePane.tabs.length <= 1
      ? null
      : { ...sourcePane, ...withoutTab(sourcePane, tabIndex) };

  return {
    source: {
      ...source,
      slots: nextSourceSlots,
      focusedPaneId:
        nextSourceSlots[sourceIndex] === null && source.focusedPaneId === sourcePaneId
          ? (nextSourceSlots.find((slot): slot is Pane => slot !== null)?.paneId ?? null)
          : source.focusedPaneId,
      maximizedPaneId:
        nextSourceSlots[sourceIndex] === null && source.maximizedPaneId === sourcePaneId
          ? null
          : source.maximizedPaneId,
    },
    target: { ...target, slots: nextTargetSlots, focusedPaneId: nextTargetPaneId },
  };
}
