// Pure `.opencode/plugins/panecrew-attention.js` (project-level — OpenCode
// auto-loads every JS/TS file under `.opencode/plugins/`, verified against
// https://opencode.ai/docs/plugins/ at implementation time) plugin-file
// writer — .scratch/pane-attention-notifications ticket 08. OpenCode has no
// config-only notify/hook mechanism like Claude Code/Gemini CLI/Copilot
// CLI — hooks are only reachable through its JS/TS plugin API, so instead
// of patching a settings file this writes a small, dedicated plugin file.
// Same whole-file-compare approach as `copilotCli.ts` (PaneCrew owns this
// file outright, nothing to merge).

export interface PatchResult {
  text: string;
  changed: boolean;
}

/** The generated plugin file's source. `\x1b`/`\x07` (hex escapes) are used
 * instead of octal `\033`/`\007` because octal escape sequences are not
 * allowed inside a JS template literal (the `$` shell tag below) — this
 * text is JS source that OpenCode itself loads and runs, not a shell
 * command string like the other adapters' `NOTIFY_COMMAND` constants. */
export const OPENCODE_PLUGIN_FILE = `// Auto-generated by PaneCrew: emits the OSC 9 signal PaneCrew's attention
// badge listens for, straight to this session's own tty — on session.idle
// (a turn finished) and permission.asked (OpenCode is waiting on you).
export const PaneCrewAttentionPlugin = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type === "session.idle") {
        await $\`printf '\\x1b]9;OpenCode is done\\x07' > /dev/tty\`;
      } else if (event.type === "permission.asked") {
        await $\`printf '\\x1b]9;OpenCode needs your attention\\x07' > /dev/tty\`;
      }
    },
  };
};
`;

/** This is a dedicated PaneCrew-owned file (not a shared settings file to
 * merge into), so "patch" is just a whole-file compare: create/overwrite if
 * different, no-op if it already matches. */
export function computePatchedConfig(existingConfigText: string | undefined): PatchResult {
  if (existingConfigText === OPENCODE_PLUGIN_FILE) {
    return { text: existingConfigText, changed: false };
  }
  return { text: OPENCODE_PLUGIN_FILE, changed: true };
}
